Bakery/Models/Flavor.cs
using System.Collections.Generic;

namespace Bakery.Models;

public class Flavor
{
  public int FlavorId { get; set; }
  public string Name { get; set; }
  public List<FlavorTreat> JoinEntities { get; }
}

Bakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;

namespace Bakery.Controllers;

public class FlavorsController : Controller
{
  private readonly BakeryContext _db;

  public FlavorsController(BakeryContext db)
  {
    _db = db;
  }

  public ActionResult Index()
  {
    List<Flavor> model = _db.Flavors.ToList();
    return View(model);
  }

[Authorize]
  public ActionResult Create()
  {
    return View();
  }

[Authorize]
  [HttpPost]
  public ActionResult Create(Flavor flavor)
  {
    if(!ModelState.IsValid)
    {
      return View(flavor);
    }
    else
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
    
  public ActionResult Details(int id)
  {
    Flavor thisFlavor = _db.Flavors
                                  .Include(flavor => flavor.JoinEntities)
                                  .ThenInclude(join => join.Treat)
                                  .FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

[Authorize]
  public ActionResult AddTreat(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
    return View(thisFlavor);
  }

[Authorize]
  [HttpPost]
  public ActionResult AddTreat(Flavor flavor, int treatId)
  {
#nullable enable
    FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
#nullable disable
    if (joinEntity == null && treatId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId});
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = flavor.FlavorId });
  }

[Authorize]
  public ActionResult Edit(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

[Authorize]
  [HttpPost]
  public ActionResult Edit(Flavor flavor)
  {
    _db.Flavors.Update(flavor);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

[Authorize]
  public ActionResult Delete(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  } 

[Authorize]
  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    _db.Flavors.Remove(thisFlavor);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

[Authorize]
  [HttpPost]
  public ActionResult DeleteJoin(int joinId)
  {
    FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
    _db.FlavorTreats.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
}

Bakery/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;

namespace Bakery.Controllers;

public class TreatsController : Controller
{
  private readonly BakeryContext _db;

  public TreatsController(BakeryContext db)
  {
    _db = db;
  }

  public ActionResult Index()
  {
    List<Treat> model = _db.Treats.ToList();
    return View(model);
  }

[Authorize]
  public ActionResult Create()
  {
    return View();
  }

[Authorize]
  [HttpPost]
  public ActionResult Create(Treat treat)
  {
    if(!ModelState.IsValid)
    {
      return View(treat);
    }
    else
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
    
  public ActionResult Details(int id)
  {
    Treat thisTreat = _db.Treats
                                .Include(treat => treat.JoinEntities)
                                .ThenInclude(join => join.Flavor)
                                .FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

// [Authorize]
  public ActionResult AddFlavor(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
    return View(thisTreat);
  }

// [Authorize]
  [HttpPost]
  public ActionResult AddFlavor(Treat treat, int flavorId)
  {
#nullable enable
    FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
    if (joinEntity == null && flavorId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId});
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = treat.TreatId });
  }

// [Authorize]
  public ActionResult Edit(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

// [Authorize]
  [HttpPost]
  public ActionResult Edit(Treat treat)
  {
    _db.Treats.Update(treat);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

// [Authorize]
  public ActionResult Delete(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  } 

// [Authorize]
  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    _db.Treats.Remove(thisTreat);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

// [Authorize]
      [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
} 

Bakery/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor
<h2>Add a Treat</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Add" />
}

Bakery/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h3>Add a flavor</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add" />
}

Bakery/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h3>Delete this flavor: @Html.DisplayFor(model => model.Name)</h3>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  <input type="submit" value="Yes, Delete" />
}

Bakery/Views/Flavors/Details.cshtml
@{
  Layout ="_Layout";
}

@model Bakery.Models.Flavor
@using Bakery.Models

<h2>@Html.DisplayFor(model => model.Name)</h2>

<h4>Treats:</h4>

@if (Model.JoinEntities.Count == 0)
{
  <p>No treats added to this flavor</p>
}
<ul>
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{join.Treat.Name}", "Details", "Treats", new { id =join.Treat.TreatId })</li>
    @using(Html.BeginForm("DeleteJoin", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Remove this treat" />
    }
  }
</ul>
<p>@Html.ActionLink("Add a treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Edit", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete", "Delete", new { id = Model.FlavorId })</p>

Bakery/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save Changes" />
}

Bakery/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models

<h2>Flavors</h2>

@if (Model.Count == 0)
{
  <p>No flavors added yet</p>
}
@foreach (Flavor flavor in Model)
{
  <p>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId }) </p>
}